import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Ensure your globals.css file contains the necessary dark mode styles */}
      </head>
      <body className={inter.className}>
        {children}
        <script src="/theme-toggle.js"></script> {/* Including the theme toggle script */}
      </body>
    </html>
  );
}
